name: DonatorJoinPlus
main: com.dbsoftwares.djp.spigot.DonatorJoinPlus
version: ${project.version}
depend: [ Vault ]
author: didjee2
api-version: '1.13'
libraries:
  - 'com.zaxxer:HikariCP:5.0.0'
  - 'org.xerial:sqlite-jdbc:3.36.0.3'
  - 'com.h2database:h2:1.4.200'